### PR TITLE
place soul in grid coords space

### PR DESCRIPTION
**Pull request by loteque**
Add the soul asset placeholder to a new meshlibray
image

Convert Ground in World Scene to it's own scene so work on it won't overwrite the world scene.
image

Add a GridMap that is synced to the camera GridMap to the Ground scene. most of this is done in gdscript but I did have to convert the Ground node from Spacial to GridMap as seen here.
image

Here is the soul asset centered on a grid cell in game:
image

### CODE REVIEW

**Comment by jonathandavidlewis** [comment]
@loteque If there is something visibly different in the editor or in running the game, can you include those visible differences here?

**Comment by loteque** [comment]
> @loteque If there is something visibly different in the editor or in running the game, can you include those visible differences here?

I updated the PR description.

**Comment by jonathandavidlewis** [comment]
@loteque The difference between reading the text files to understand what was done and seeing your images is night and day. It gives me so much more confidence in what I am looking at even when I pull it up on my own machine. Thank you!

**Review by jonathandavidlewis — APPROVED** [review]
Very nice. I ran a local test. Looks good. 💯

**Pull request merged**
